#!/usr/bin/env python

# Version 1.0
# Author Alexis Blanchet-Cohen
# Date: 24/03/2014

import argparse
import ConfigParser
import glob

parser = argparse.ArgumentParser(description='Generate the coverage bedgraph file.')
parser.add_argument("-f", "--file", help="Coverage file generated by bismark.", required=True)
args = parser.parse_args()

# Open coverage file.
coverageFile = open(args.file)

# Create bedgraph file
coverageBedgraph =  args.file.replace("bismark.cov", "cov.bedGraph")
coverageBedgraph = open(coverageBedgraph, "w")
coverageBedgraph.write("track type=bedGraph\n")

for line in coverageFile:
    fields = line.split()
    chromosome = fields[0]
    start = fields[1]
    end = fields[2]
    methylated = fields[4]
    unmethylated = fields[5]
    coverage = str(int(methylated) + int(unmethylated)) 
    coverageBedgraph.write(chromosome + "\t" + start + "\t" + end + "\t" + coverage + "\n")


